version: "3"

services:
  attacker:
    networks:
      network:
        ipv4_address: 192.168.0.10
  client:
    networks:
      network:
        ipv4_address: 192.168.0.20
  server:
    networks:
      network:
        ipv4_address: 192.168.0.30

networks:
  network:
    ipam:
      driver: default
      config:
        - subnet: "192.168.0.0/24"
