version: "3"

services:
  client:
    build: .
    stdin_open: true
    tty: true
    networks:
      app_net:
        ipv4_address: 192.168.0.10
  attacker:
    build: .
    stdin_open: true
    tty: true
    networks:
      app_net:
        ipv4_address: 192.168.0.20
      
networks:
  app_net:
    ipam:
      driver: default
      config:
        - subnet: "192.168.0.0/24"